name: Update dependencies

on:
  schedule:
    - cron: "0 0 1 * *"  # Обновление зависимостей раз в месяц
  workflow_dispatch:  # Возможность запуска вручную

env:
  PYTHON_VERSION: '3.11'
  CI_DEBUG: true
  POETRY_VERSION: '2.1.3'
  PYINSTALLER_VERSION: '6.14.2'

jobs:
  update-dependencies:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==${{ env.POETRY_VERSION }}
        shell: bash

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
        shell: bash

      - name: Create virtual environment
        run: |
          poetry env use python
        shell: bash

      - name: Install Project Dependencies
        run: |
          poetry lock
          poetry install --no-interaction --no-root
          poetry install --no-interaction --with dev --all-extras
          poetry run pip install pyinstaller==${{ env.PYINSTALLER_VERSION }}
        shell: bash

      - name: Clear Poetry cache
        run: |
          rm -rf ~/.cache/pypoetry

      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-

      - name: Update dependencies
        run: |
          poetry self update
          poetry lock
          poetry install
          poetry update
        env:
          POETRY_CACHE_DIR: ~/.cache/pypoetry

      - name: Configure Git user
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes to main
        run: |
          git add poetry.lock
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update dependencies"
            git push origin main
          fi
